kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: squash-graphql
  labels:
    app: squash
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: squash
        tier: graphql 
    spec:
      containers:
        - name: nginx
          imagePullPolicy: "Always"
          image: lsstsqre/squash-graphql-nginx:{{ TAG }}
          lifecycle:
            preStop:
              exec:
                command: ['/usr/sbin/nginx','-s','quit']
          volumeMounts:
            - name: nginx-conf
              mountPath: '/etc/nginx/conf.d'
            - name: tls-certs
              mountPath: '/etc/tls'
        - name: api
          imagePullPolicy: "Always"
          image: lsstsqre/squash-graphql:{{ TAG }}
          ports:
            - name: http
              containerPort: 8000
          env:
          - name: SQUASH_DB_HOST
          # squash-db resolves to the Cluster IP address
            value: squash-db
          - name: SQUASH_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-passwd
                key: 'passwd.txt'
          - name: ALLOWED_HOSTS
            value: {{ SQUASH_API_HOST }}
      volumes:
        - name: tls-certs
          secret:
            secretName: tls-certs
        - name: nginx-conf
          configMap:
            name: squash-graphql-nginx-conf
            items:
              - key: 'nginx.conf'
                path: 'nginx.conf'

